const fs = require('fs');
const path = require('path');
const { getProjectState } = require('../lib/config');
const { runAudit } = require('./audit');
const { runCleanup } = require('./cleanup');
const { runOverview } = require('./overview');

const PLANS_DIR = '.cursor/plans';

/**
 * Generate a step-by-step migration plan and save to .cursor/plans/migration-[from]-to-[to].md
 * @param {string} cwd
 * @param {{ from: string, to: string }} opts - e.g. { from: 'pages router', to: 'app router' }
 * @returns {{ planPath: string, steps: string[] }}
 */
function runMigrate(cwd = process.cwd(), opts = {}) {
  const state = getProjectState(cwd);
  if (!state) {
    return { error: 'No aac.config.yml found. Run `aac init` first.', planPath: null };
  }
  const { root, config } = state;
  const from = (opts.from || 'current').replace(/\s+/g, '-').toLowerCase();
  const to = (opts.to || 'target').replace(/\s+/g, '-').toLowerCase();
  const planDir = path.join(root, PLANS_DIR);
  if (!fs.existsSync(planDir)) {
    fs.mkdirSync(planDir, { recursive: true });
  }
  const planFilename = `migration-${from}-to-${to}.md`;
  const planPath = path.join(planDir, planFilename);

  const auditResult = runAudit(cwd, { json: true });
  const cleanupResult = runCleanup(cwd, { json: true });
  const overviewResult = runOverview(cwd, { json: true });

  const steps = [
    '# Migration plan: ' + (opts.from || 'current') + ' → ' + (opts.to || 'target'),
    '',
    '## Baseline (run before starting)',
    '- [ ] Run `aac audit` and fix blocking errors',
    '- [ ] Run `aac cleanup` and remove or integrate unused code',
    '- [ ] Run `aac overview` and note current structure',
    '',
    '## Step 1: Audit current state',
    '- Map what exists and what will be affected',
    '- List every file that will change',
    '',
    '## Step 2: Set up new scaffold without removing old',
    '- Add new structure (e.g. app/ routes) alongside existing',
    '- Do not delete old system yet',
    '',
    '## Step 3: Feature-flag the switch',
    '- Use a flag to toggle between old and new (e.g. USE_NEW_ROUTER)',
    '- Validate new system thoroughly',
    '',
    '## Step 4: Migrate layer by layer',
    '- Order: ui → content → layout → app',
    '- One axis at a time; no drive-by refactors',
    '',
    '## Step 5: Cleanup after each layer',
    '- Run `aac cleanup` after each layer',
    '- Remove dead code before moving on',
    '',
    '## Step 6: Update aac.config.yml',
    '- Reflect new structure in layers and rules',
    '',
    '## Step 7: Final verification',
    '- [ ] `aac audit` — 0 errors',
    '- [ ] `aac overview` — structure matches intent',
    '- [ ] `npx tsc --noEmit` (if applicable)',
    '- [ ] Build and manual smoke test',
    '',
    '---',
    'Generated by `aac migrate`. Verify checklist after every step.',
  ];

  const baseline = [
    '## Baseline snapshot (at plan creation)',
    '',
    '### Audit',
    `- Errors: ${(auditResult.errors || []).length}`,
    `- Warnings: ${(auditResult.warnings || []).length}`,
    `- Files scanned: ${auditResult.filesScanned || 0}`,
    '',
    '### Cleanup',
    `- Unused imports: ${(cleanupResult.unusedImports || []).length}`,
    `- Unused components: ${(cleanupResult.unusedComponents || []).length}`,
    '',
  ];

  const content = steps.slice(0, 3).join('\n') + '\n' + baseline.join('\n') + '\n' + steps.slice(3).join('\n');
  fs.writeFileSync(planPath, content, 'utf8');

  return { planPath: path.relative(root, planPath), steps, error: null };
}

module.exports = { runMigrate, PLANS_DIR };
